// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDcZgwb4F8WYFvX8NeJn0Xp-wId-duVeU',
    appId: '1:653024658804:web:84357f92bbfc9f8f8f1821',
    messagingSenderId: '653024658804',
    projectId: 'weedor-math-genius',
    authDomain: 'weedor-math-genius.firebaseapp.com',
    storageBucket: 'weedor-math-genius.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGK1yKCNO1NSEdoMLPmPdD-nsnhZMs9yk',
    appId: '1:653024658804:android:1aa28be878c0b1668f1821',
    messagingSenderId: '653024658804',
    projectId: 'weedor-math-genius',
    storageBucket: 'weedor-math-genius.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDcZgwb4F8WYFvX8NeJn0Xp-wId-duVeU',
    appId: '1:653024658804:ios:84357f92bbfc9f8f8f1821',
    messagingSenderId: '653024658804',
    projectId: 'weedor-math-genius',
    storageBucket: 'weedor-math-genius.firebasestorage.app',
    iosBundleId: 'com.mathgenius.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwvubOsRM-an7YvfJd3iUmNlrAxgyR0nI',
    appId: '1:653024658804:ios:3158cef644d5dc648f1821',
    messagingSenderId: '653024658804',
    projectId: 'weedor-math-genius',
    storageBucket: 'weedor-math-genius.firebasestorage.app',
    iosBundleId: 'com.weedor.mathGenius',
  );

}